### ISSUE TITLE
Introduce MessageValidator concept

### ISSUE THREAD

**Issue by rdohms** [chimeraphp/foundation#33]
Currently, validation happens after deserialization. This is mostly fine, but poses a problem when for example deserializing into a UUID object, as it will throw its own exception, and thus the user gets an exception, not a nice validation message.

It also blocks another feature, deserializing based on property type hints, as once more all the type validation triggers exceptions.

I was thinking, what if we introduce validation on the message input level, before deserialization, on the raw json input.

The issue then becomes "where do the rules live?
For this we could do some smart handling, we already know the object we will deserialize into, we could thus, load annotations from this object (hijack the way Validator does it internally) and use those to validate the raw array input.

For this, we would need to hook into the `ExecuteCommand` class, as its the moment where messages are created and we know the target object. (or is there another place to hook in?)

**Comment by lcobucci** [comment]
This is honestly out of the scope of this library, even the post deserialisation validation you mention is a Usabilla-specific thing.

The best way to handle this is having a middleware to verify the message structure. A good example of such a middleware can be found in https://github.com/thephpleague/openapi-psr7-validator

**Comment by rdohms** [comment]
Is it possible to inject said middleware before command deserialization?
How are other projects doing validation?

**Comment by lcobucci** [comment]
@rdohms all http middleware happen before deserialisation. The way you have it configured is a bus middleware, which is why it happens after deserialisation.

**Comment by rdohms** [comment]
Any pointers to how I could get the command class injected into the http middleware?

**Comment by lcobucci** [comment]
You're not gonna do that with the command as you want to handle that BEFORE deserialisation. You do it with the request body.

**Comment by rdohms** [comment]
Yes I understand that. But I would like to know which command class it expects to deserialize into afterwards. This way I can do some magic and load validation from there instead of from another source.

Is there anything I can inject that can tell me the route configuration?

**Comment by lcobucci** [comment]
Nope.
What you can do is decorate the `MessageCreator` with your validation logic (it receives the message to be created and the `Input`).

Since you're using JMS serializer [this is the implementation](https://github.com/chimeraphp/serialization-jms/blob/master/src/ArrayTransformer.php) you'd be decorating, though that is irrelevant since you should be depending on the interface to handle this.

**Comment by rdohms** [comment]
Any pointers as to where I can override that? We are light on docs so I'm really trying to get the full picture.

**Comment by lcobucci** [comment]
You should do that on the DI container level. On your app (or one of libs), use SF DI's decorator functionality to decorate the [`ArrayTransformer` service](https://github.com/chimeraphp/di-symfony/blob/master/config/serialization-jms.xml#L10-L12).

You can find how to do that on SF docs :+1:
